## 🟦Task 1: NumPy Basics

# Part 1: Array Creation

In [41]:
import numpy as np

In [42]:
arr=np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [43]:
arr2=np.arange(0,20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr3=np.linspace(1,5,10)
arr3

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## Part 2: Special Arrays

In [45]:
array1=np.zeros((3,3))
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array2=np.ones((2,4))
array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
array3=np.empty((2,2))
array3

array([[4.62012217e-308, 5.64091987e-298],
       [4.44368951e-259, 1.81580478e-297]])

In [8]:
array4=np.full((2, 2), np.nan)
array4

array([[nan, nan],
       [nan, nan]])

In [9]:
array5=np.identity(3)
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
array6=np.eye(3)
array6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Part 3: Shape & Reshape

In [11]:
arr4=np.array([10, 20, 30, 40, 50])
arr4.shape

(5,)

In [46]:
arr5=np.arange(20)


In [47]:
arr5.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Part 4: Data Type & Statistics

In [14]:
arr6=np.array([10, 20, 30, 40, 50])
arr6.dtype

dtype('int64')

In [15]:
arr7=np.array([10, 20, 30, 40, 50])
arr7.astype(float)

array([10., 20., 30., 40., 50.])

In [16]:
arr8=np.array([10, 20, 30, 40, 50])
arr8.mean()

np.float64(30.0)

In [17]:
arr9=np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]) #2D
arr9.mean(axis=1)
arr9.mean(axis=0)


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Part 5: Array Operations

In [48]:
arr10 = np.array([10, 20, 60, 40, 90])
print("Original Array:")
print(arr10)
grad = np.gradient(arr10)
print("\nGradient of arr10:")
print(grad)

Original Array:
[10 20 60 40 90]

Gradient of arr10:
[10. 25. 10. 15. 50.]


In [19]:
conditions = [
    arr10 < 10,                  
    (arr10 >= 10) & (arr10 <= 30), 
    arr10 > 30                    
]

choices = ['Low', 'Medium', 'High'] 

arr_classified = np.select(conditions, choices, default='Unknown')
print(arr_classified)


['Medium' 'Medium' 'High' 'High' 'High']


In [20]:
arr_appended = np.append(arr10, [60, 70, 80])
print(arr_appended)


[10 20 60 40 90 60 70 80]


## 🟩Task 2: Pandas Basics (Data Handling & Cleaning)

## Part 1: Pandas Objects

In [21]:
import pandas as pd

In [22]:
age=pd.Series([18, 19, 20, 21])
age

0    18
1    19
2    20
3    21
dtype: int64

In [23]:
arr22=np.array(age)
arr22

array([18, 19, 20, 21])

## Part 2: DataFrame Creation

In [24]:
data = {
    'Name': ['Sally', 'Ali', 'Amany', 'Ahmad'],
    'Age': [18, 19, 20, 21],
    'Math_Score': [85, 72, 90, 65],
    'Gender': ['Female', 'Male', 'Female', 'Male']
}

In [25]:
df = pd.DataFrame(data)
df

Name  Age  Math_Score  Gender
0  Sally   18          85  Female
1    Ali   19          72    Male
2  Amany   20          90  Female
3  Ahmad   21          65    Male

In [26]:
df.info

<bound method DataFrame.info of     Name  Age  Math_Score  Gender
0  Sally   18          85  Female
1    Ali   19          72    Male
2  Amany   20          90  Female
3  Ahmad   21          65    Male>

In [27]:
df.describe()

Age  Math_Score
count   4.000000    4.000000
mean   19.500000   78.000000
std     1.290994   11.518102
min    18.000000   65.000000
25%    18.750000   70.250000
50%    19.500000   78.500000
75%    20.250000   86.250000
max    21.000000   90.000000

## Part 3: Indexing & Filtering

In [28]:
df['Math_Score']

0    85
1    72
2    90
3    65
Name: Math_Score, dtype: int64

In [29]:
df.loc[:, ['Name', 'Math_Score']]


Name  Math_Score
0  Sally          85
1    Ali          72
2  Amany          90
3  Ahmad          65

In [30]:
df.iloc[0:2, 1:3]


Age  Math_Score
0   18          85
1   19          72

In [31]:
high_scores = df[df['Math_Score'] > 70]
high_scores


Name  Age  Math_Score  Gender
0  Sally   18          85  Female
1    Ali   19          72    Male
2  Amany   20          90  Female

## Part 4: Data Cleaning

In [32]:
df.loc[3, 'Math_Score'] = np.nan
df

Name  Age  Math_Score  Gender
0  Sally   18        85.0  Female
1    Ali   19        72.0    Male
2  Amany   20        90.0  Female
3  Ahmad   21         NaN    Male

In [33]:
mean_score = df['Math_Score'].mean()  
df['Math_Score'] = df['Math_Score'].fillna(mean_score)
df


Name  Age  Math_Score  Gender
0  Sally   18   85.000000  Female
1    Ali   19   72.000000    Male
2  Amany   20   90.000000  Female
3  Ahmad   21   82.333333    Male

In [34]:
df = df.drop(columns=['Age'])
df


Name  Math_Score  Gender
0  Sally   85.000000  Female
1    Ali   72.000000    Male
2  Amany   90.000000  Female
3  Ahmad   82.333333    Male

## Part 5: Apply & Transformation

In [35]:
df['Result'] = df['Math_Score'].apply(lambda x: 'Fail' if x < 50 else 'Pass')
df


Name  Math_Score  Gender Result
0  Sally   85.000000  Female   Pass
1    Ali   72.000000    Male   Pass
2  Amany   90.000000  Female   Pass
3  Ahmad   82.333333    Male   Pass

In [36]:
gender_dummies = pd.get_dummies(df['Gender'], dtype=int)

df = pd.concat([df, gender_dummies], axis=1)
df = df.drop(columns=['Gender'])

df


Name  Math_Score Result  Female  Male
0  Sally   85.000000   Pass       1     0
1    Ali   72.000000   Pass       0     1
2  Amany   90.000000   Pass       1     0
3  Ahmad   82.333333   Pass       0     1

## Part 6: Combining & Reshaping

In [37]:
df2 = pd.DataFrame({
    'Name': ['Sara', 'Eman'],
    'Math_Score': [78, 88],
    'Result': ['Pass', 'Pass'],
    'Female': [1, 0],
    'Male': [0, 1]
})


In [38]:
df2

Name  Math_Score Result  Female  Male
0  Sara          78   Pass       1     0
1  Eman          88   Pass       0     1

In [39]:
df_combined = pd.concat([df, df2], ignore_index=True)
df_combined


Name  Math_Score Result  Female  Male
0  Sally   85.000000   Pass       1     0
1    Ali   72.000000   Pass       0     1
2  Amany   90.000000   Pass       1     0
3  Ahmad   82.333333   Pass       0     1
4   Sara   78.000000   Pass       1     0
5   Eman   88.000000   Pass       0     1

In [40]:
df_combined.groupby('Female')['Math_Score'].mean()


Female
0    80.777778
1    84.333333
Name: Math_Score, dtype: float64